# Generated by Django 2.2.8 on 2019-12-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('threshold_balance', models.IntegerField()),
                ('threshold_date', models.DateField()),
                ('previous_withdrawal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('balance_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FireDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.IntegerField(default=0)),
                ('fire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fires.Fire')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fires.Fund')),
            ],
            options={
                'unique_together': {('fund', 'fire')},
            },
        ),
        migrations.AddField(
            model_name='fire',
            name='funds',
            field=models.ManyToManyField(through='fires.FireDistribution', to='fires.Fund'),
        ),
    ]
